apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: macro-mate-mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: mongodb
    targetRevision: 12.1.16
    helm:
      values: |
        architecture: replicaset
        image:
          tag: 4.2.21-debian-10-r8
        auth:
          enabled: true
          rootPassword: "rootpw"
          username: "macro-mate"
          password: "password"
          database: "off"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: macro-mate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true